---
title: "Polski Twitter - Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: [ "twitter", "facebook", "menu" ]
    self_contained: no
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(tidytext)
library(wordcloud)
library(stringr)
library(shiny)

pl_stop_words <- read_lines("/home/lemur/RProjects/TwitterTrends/polish_stopwords.txt")
theme_set(theme_minimal())
```

```{r load_saved_data, message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
tweets <- readRDS("/home/lemur/RProjects/TwitterTrends/tweets.Rds")
```

```{r filter_data, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# potrzebne kolumny
tweets_an <- tweets %>%
   select(screen_name, user_id, created_at, text, trend, trend_n,
          retweet_count, favorite_count, status_id,
          source) %>%
   distinct() %>%
   mutate(created_at = with_tz(created_at)) %>%
   mutate(created_at = make_datetime(year(created_at), month(created_at), day(created_at),
   											 hour(created_at), minute(created_at), 0)) %>%
   mutate(text = gsub("\n", " ", text, fixed = TRUE))


# wyfiltrowanie zbednych twittów
tweets_an <- tweets_an %>%
   # boty i spamerzy
   filter(!source %in% c("Poland Trends")) %>%
   # tylko ostatnie 12 godzin
   filter(created_at >= Sys.time() - hours(12)) %>%
  mutate(created_at = with_tz(created_at, "Europe/Warsaw"))

trends <- tweets_an %>%
   select(trend, trend_n) %>%
   distinct() %>%
   arrange(trend_n) %>%
   .[,1]
```

```{r word_cloud_data, message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
# chmurki słów
words <- tweets_an %>%
   # bez linków
   mutate(text = gsub(" ?(f|ht)tp(s?)://(.*)[.][a-z]+", "", text)) %>%
   unnest_tokens(word, text, token="words") %>%
   count(word, trend) %>%
   ungroup() %>%
   # usuniecie z chmurki slowa - trendu (oczywiscie ono dominuje)
   filter(word != str_to_lower(str_replace_all(trend, "#", ""))) %>%
   # bez stop words
   filter(!word %in% pl_stop_words) %>%
	filter(!word %in% stop_words$word)
```

Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r}
radioButtons("trend_input",
            label = "Trend:",
            choices = trends,
            selected = trends[1])

```

Aktualizacja: `r format(max(with_tz(tweets_an$created_at, "Europe/Warsaw")), "%Y-%m-%d, %H:%M")`

Autor: [Łukasz Prokulski](http://prokulski.net/?utm_source=shiny&utm_medium=shiny_twitter)

Kilka słów o tym [jak to działa](http://prokulski.net/index.php/2017/06/20/maszynka-do-czytania-twittera/?utm_source=shiny&utm_medium=shiny_twitter)


Column {data-width=300}
-----------------------------------------------------------------------

### Chmura słów

```{r}
renderPlot({
   words_tmp <- filter(words, trend == input$trend_input)

   wordcloud(words_tmp$word, words_tmp$n,
#             scale = c(2, 0.5),
             min.freq = mean(words_tmp$n)+sd(words_tmp$n),
             colors = RColorBrewer::brewer.pal(12, "Paired"))
})
```


### Czas

```{r}
renderPlot({
   tweets_an_tmp <- filter(tweets_an, trend == input$trend_input)
   tweets_an_tmp %>%
      count(created_at) %>%
      ungroup() %>%
      ggplot() +
      geom_point(aes(created_at, n), color="darkgreen", alpha = 0.3, size = 3) +
      expand_limits(y = 0) +
      labs(x="Czas", y="Liczba twittów",
           title = paste0("Trend: ", input$trend_input))  
})
```


Column {data-width=500}
-----------------------------------------------------------------------

### Twitty

```{r}
renderTable({
  tweets_an %>%
    filter(trend == input$trend_input) %>%
    mutate(score = retweet_count + favorite_count) %>%
    filter(score > 0) %>%
    arrange(desc(score)) %>%
    mutate(Time = ifelse(day(created_at) == day(Sys.time()),
                           format(created_at, "%H:%M"),
                           format(created_at, "%Y-%m-%d, %H:%M"))) %>%
    mutate(link = paste0("<a href=\"https://twitter.com/",
                           screen_name,
                           "/status/",
                           status_id,"\">", Time, "</a>")) %>%
    select(Tweet=text, Author=screen_name, Time=link,
             RTs=retweet_count, FAVs=favorite_count)
}, hover = TRUE, spacing = "s", escape = FALSE, sanitize.text.function = function(x) x)
```

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1427545-15', 'auto');
  ga('send', 'pageview');

</script>
